- name: Initialize Android Project & Configs
        run: |
          rm -rf android ios windows macos linux web
          flutter create . --org com.syriacash --project-name syria_cash --platforms=android
          flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Upload APK file
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
